# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:36:46+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity

from models import (
    BalanceResponse,
    Field400,
    Field401,
    Field403,
    Field422,
    IBANResult,
    IBANResultBasic,
)

app = MCPProxy(
    contact={'email': 'samy@ibanapi.com'},
    description='IBANAPI OpenApi documentation',
    title='IBANAPI OpenApi Documentation',
    version='1.0.0',
    servers=[{'description': 'IBANAPI Server', 'url': 'https://api.ibanapi.com/v1'}],
)


@app.get(
    '/balance',
    description=""" Returns the account balance and expiry """,
    tags=['account_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_balance():
    """
    Get Account Balance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/validate',
    description=""" Returns the validation results """,
    tags=['iban_verification'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def validate_i_b_a_n(iban: str):
    """
    Validate IBAN
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/validate-basic',
    description=""" Returns the basic validation results """,
    tags=['iban_verification'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def validate_i_b_a_n_basic(iban: str):
    """
    Validate IBAN Basic
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
