# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:36:46+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Field400(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, examples=['{}'])
    message: Optional[str] = Field(None, examples=['Your balance is exhausted'])
    result: Optional[int] = Field(None, examples=['400'])


class Field401(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, examples=['{}'])
    message: Optional[str] = Field(None, examples=['Your package has expired'])
    result: Optional[int] = Field(None, examples=['401'])


class Field403(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, examples=['{}'])
    message: Optional[str] = Field(None, examples=['Invalid API Key'])
    result: Optional[int] = Field(None, examples=['403'])


class Field422(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, examples=['{}'])
    message: Optional[str] = Field(None, examples=['API key is missing'])
    result: Optional[int] = Field(None, examples=['422'])


class BalanceResponse(BaseModel):
    data: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {'bank_balance': 100, 'basic_balance': 2000, 'expiry_date': '2021-05-16'}
        ],
    )
    message: Optional[str] = Field(None, examples=['SUCCESS'])
    result: Optional[int] = Field(None, examples=['200'])


class IBANResult(BaseModel):
    data: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {
                'bank': {
                    'address': 'TORNIMAE 2 FLOOR 10',
                    'bank_name': 'AS SEB PANK',
                    'bic': 'EEUHEE2X',
                    'city': 'TALLINN',
                    'phone': '',
                    'state': '',
                    'zip': '15010',
                },
                'bank_account': '00102014568',
                'bban': '1000001020145685',
                'country_code': 'EE',
                'country_name': 'Estonia',
                'currency_code': 'EUR',
                'iso_alpha3': 'EST',
                'sepa': {
                    'sepa_b2b': 'No',
                    'sepa_card_clearing': 'No',
                    'sepa_credit_transfer': 'Yes',
                    'sepa_direct_debit': 'No',
                    'sepa_sdd_core': 'No',
                },
                'sepa_member': 'Yes',
            }
        ],
    )
    expremental: Optional[int] = Field(None, examples=['0'])
    message: Optional[str] = Field(None, examples=['Valid IBAN Number'])
    result: Optional[int] = Field(None, examples=['200'])
    validations: Optional[List] = Field(
        None,
        examples=[
            [
                {'message': 'Valid IBAN length', 'result': 200},
                {'message': 'Valid IBAN Checksum', 'result': 200},
            ]
        ],
    )


class IBANResultBasic(BaseModel):
    data: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {
                'bban': '1000001020145685',
                'country_code': 'EE',
                'country_name': 'Estonia',
                'currency_code': 'EUR',
                'iso_alpha3': 'EST',
                'sepa': [],
                'sepa_member': 'Yes',
            }
        ],
    )
    expremental: Optional[int] = Field(None, examples=['0'])
    message: Optional[str] = Field(None, examples=['Valid IBAN Number'])
    result: Optional[int] = Field(None, examples=['200'])
    validations: Optional[List] = Field(
        None,
        examples=[
            [
                {'message': 'Valid IBAN length', 'result': 200},
                {'message': 'Valid IBAN Checksum', 'result': 200},
            ]
        ],
    )
